name: CI Makefile
on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - 'latest'
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.runner }} ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Regular test
        run: |
            uname -a
            apt-get install -y libgtk2.0-dev libgif-dev libjpeg-dev libtiff-dev libxpm-dev libwebp-dev libfribidi-dev libharfbuzz-dev libthai-dev
            cpanm --notest Test::Pod
            perl Makefile.PL
            make
            make test
  strawberry:
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - 'latest'
    runs-on: windows-latest
    name: Perl ${{ matrix.runner }} ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: ${{ ( startsWith( matrix.runner, 'windows-' ) && 'strawberry' ) || 'default' }}
      - name: Regular test
        run: |
            uname -a
            cpanm --notest Test::Pod
            perl Makefile.PL
            make
            make test
