name: CI Makefile
on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - 'latest'
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Linux ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: |
            uname -a
            apt-get install -y libgtk2.0-dev libgif-dev libjpeg-dev libtiff-dev libxpm-dev libwebp-dev libfribidi-dev libharfbuzz-dev libthai-dev
            cpanm --notest Test::Pod
      - name: Build
        run: |
            perl Makefile.PL
            make
      - name: Test
        run: |
            make test
  strawberry:
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - 'latest'
    runs-on: windows-latest
    name: Strawberry ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
          distribution: strawberry
      - name: Prepare
        run: |
            uname -a
            cpanm --notest Test::Pod
      - name: Build
        run: |
            perl Makefile.PL
            make
      - name: Test
        run: |
            make test
