name: CI Makefile
on:
    push:
        branches: '*'
    pull_request:
        branches: '*'
jobs:
  perl-job:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, windows-latest]
        perl-version:
          - 'latest'
#          - '5.32'
    runs-on: ${{matrix-runner}}
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}     # https://hub.docker.com/r/perldocker/perl-tester
    name: Perl ${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Regular tests
        if: matrix.runner == 'ubuntu.latest'
        run: |
            apt-get install -y libgtk2.0-dev libgif-dev libjpeg-dev libtiff-dev libxpm-dev libwebp-dev libfribidi-dev libharfbuzz-dev libthai-dev
        run: |
            uname -a
            cpanm --notest Test::Pod
            perl Makefile.PL
            make
            make test
